#!/usr/bin/env python3
"""
Configuración específica para ejecutar el bot desde móvil cuando no se puede usar PC en el trabajo
"""

def soluciones_movil_trabajo():
    """Soluciones específicas para trabajar sin PC"""
    
    print("SOLUCIONES PARA BOT SIN PC EN EL TRABAJO")
    print("=" * 50)
    print()
    
    print("PROBLEMA: No puedes usar PC en el trabajo")
    print("SOLUCIÓN: Bot 100% en la nube + control móvil")
    print()
    
    print("OPCIÓN 1: PYTHONANYWHERE (GRATIS - RECOMENDADO)")
    print("-" * 45)
    print("Ventajas:")
    print("  + GRATIS")
    print("  + Configuración en 10 minutos")
    print("  + Acceso desde cualquier móvil")
    print("  + Python, Git, SQLite incluidos")
    print()
    print("Limitaciones:")
    print("  - 2 horas al día (gratuito)")
    print("  - 1 proceso simultáneo")
    print("  - Sin acceso 24/7")
    print()
    print("Ideal para:")
    print("  + Uso moderado (mañana y tarde)")
    print("  + Pruebas iniciales")
    print("  + Si no necesitas 24/7")
    print()
    
    print("OPCIÓN 2: REPLIT (GRATIS - ALTERNATIVA)")
    print("-" * 40)
    print("Ventajas:")
    print("  + GRATIS")
    print("  + Always On gratuito")
    print("  + Interfaz web amigable")
    print("  + Python, Git incluidos")
    print()
    print("Limitaciones:")
    print("  - Requiere keep-alive (cada 10 min)")
    print("  - Puede dormir por inactividad")
    print("  - Menos estable que PythonAnywhere")
    print()
    
    print("OPCIÓN 3: VPS DIGITALOCEAN ($5/mes - MEJOR)")
    print("-" * 45)
    print("Ventajas:")
    print("  + 24/7 sin interrupciones")
    print("  + Control completo")
    print("  + IP dedicada")
    print("  + Múltiples procesos")
    print("  + Acceso SSH desde móvil")
    print()
    print("Costo:")
    print("  - $5/mes (~5 euros)")
    print("  - Primer mes gratis (código)")
    print("  - Cancelable anytime")
    print()
    
    print("OPCIÓN 4: GLITCH (GRATIS - EXPERIMENTAL)")
    print("-" * 40)
    print("Ventajas:")
    print("  + GRATIS")
    print("  + Fácil de usar")
    print("  + Bueno para pruebas")
    print()
    print("Limitaciones:")
    print("  - 4000 horas/mes (~5.5 horas/día)")
    print("  - Se duerme por inactividad")
    print("  - Menos potente")
    print()
    
    print("CONFIGURACIÓN PASO A PASO - PYTHONANYWHERE")
    print("=" * 50)
    print()
    
    print("1. REGISTRO (5 minutos)")
    print("-" * 25)
    print("  1. Ve a www.pythonanywhere.com")
    print("  2. Regístrate con email (gratis)")
    print("  3. Verifica email")
    print("  4. Listo!")
    print()
    
    print("2. SUBIR CÓDIGO (10 minutos)")
    print("-" * 30)
    print("  1. Inicia sesión en PythonAnywhere")
    print("  2. Ve a 'Consoles' > 'Bash'")
    print("  3. Ejecuta estos comandos:")
    print("     git clone https://github.com/damianortells4-code/bot-inmobiliario-2.0")
    print("     cd bot-inmobiliario-2.0")
    print("     pip3 install -r requirements.txt")
    print("  4. Espera a que instale todo")
    print()
    
    print("3. CONFIGURAR VARIABLES (5 minutos)")
    print("-" * 35)
    print("  1. Ve a 'Files' > 'bot-inmobiliario-2.0'")
    print("  2. Edita 'config.py' (o crea uno nuevo)")
    print("  3. Añade tus variables de Telegram:")
    print("     TELEGRAM_BOT_TOKEN = 'tu_token'")
    print("     TELEGRAM_CHAT_ID = 'tu_chat_id'")
    print("  4. Guarda el archivo")
    print()
    
    print("4. PROGRAMAR EJECUCIÓN (5 minutos)")
    print("-" * 35)
    print("  1. Ve a 'Tasks' > 'Create a new task'")
    print("  2. Configura:")
    print("     - Type: Python")
    print("     - Command: /home/tuusuario/bot-inmobiliario-2.0/main.py")
    print("     - Schedule: Every 10 minutes")
    print("     - Hour: 08:00 - 20:00 (horario laboral)")
    print("  3. Guarda la tarea")
    print()
    
    print("5. PROBAR Y MONITOREAR")
    print("-" * 25)
    print("  1. Ve a 'Tasks' y haz clic en 'Run now'")
    print("  2. Revisa el log para ver si funciona")
    print("  3. Recibirás notificaciones en Telegram")
    print("  4. Desde móvil puedes ver los resultados")
    print()
    
    print("CONFIGURACIÓN PASO A PASO - VPS DIGITALOCEAN")
    print("=" * 50)
    print()
    
    print("1. CREAR SERVIDOR (10 minutos)")
    print("-" * 30)
    print("  1. Ve a www.digitalocean.com")
    print("  2. Regístrate (primer mes gratis con código)")
    print("  3. Crea 'Droplet' > Ubuntu 22.04")
    print("  4. Plan básico $5/mes")
    print("  5. Elige región cercana (ej: Frankfurt)")
    print("  6. Crea servidor")
    print()
    
    print("2. ACCEDER Y CONFIGURAR (15 minutos)")
    print("-" * 35)
    print("  1. Recibirás email con IP del servidor")
    print("  2. Desde móvil: usa app 'JuiceSSH' (Android)")
    print("  3. Conecta: root@IP_DEL_SERVIDOR")
    print("  4. Ejecuta:")
    print("     apt update && apt install -y python3 python3-pip git")
    print("     git clone https://github.com/damianortells4-code/bot-inmobiliario-2.0")
    print("     cd bot-inmobiliario-2.0")
    print("     pip3 install -r requirements.txt")
    print()
    
    print("3. CONFIGURAR Y EJECUTAR (10 minutos)")
    print("-" * 35)
    print("  1. Edita config.py con tus datos Telegram")
    print("  2. Ejecuta en modo fondo:")
    print("     nohup python3 main.py > bot.log 2>&1 &")
    print("  3. Verifica que funciona:")
    print("     tail -f bot.log")
    print("  4. Listo! 24/7 desde móvil")
    print()
    
    print("CONTROL DESDE MÓVIL")
    print("=" * 20)
    print()
    
    print("APPS RECOMENDADAS:")
    print("-" * 20)
    print("Android:")
    print("  + Termux: Terminal y SSH")
    print("  + JuiceSSH: Conexiones SSH guardadas")
    print("  + Telegram: Notificaciones y control")
    print("  + Chrome: Acceso web a paneles")
    print()
    print("iOS:")
    print("  + Blink SSH: Cliente SSH ($20)")
    print("  + Termius: SSH gratuito")
    print("  + Telegram: Notificaciones")
    print("  + Safari: Acceso web")
    print()
    
    print("FUNCIONES DESDE MÓVIL:")
    print("-" * 25)
    print("  + Ver logs del bot")
    print("  + Reiniciar bot si se detiene")
    print("  + Recibir notificaciones de leads")
    print("  + Configurar parámetros")
    print("  + Ver estadísticas")
    print()
    
    print("RECOMENDACIÓN FINAL")
    print("=" * 20)
    print()
    
    print("PARA EMPEZAR: PythonAnywhere (GRATIS)")
    print("-" * 35)
    print("  + Cero costo")
    print("  + Configuración en 30 minutos")
    print("  + Funciona desde cualquier móvil")
    print("  + Ideal para aprender y probar")
    print()
    
    print("PARA USO SERIO: VPS DigitalOcean ($5/mes)")
    print("-" * 40)
    print("  + 24/7 sin límites")
    print("  + Control total")
    print("  + Mejor rendimiento")
    print("  + Inversión mínima")
    print()
    
    return {
        'gratis': 'PythonAnywhere',
        'pago': 'DigitalOcean VPS',
        'alternativa': 'Replit'
    }

if __name__ == "__main__":
    soluciones_movil_trabajo()
