import config
from portales_comun import PALABRAS_INMOBILIARIA

# Señales de anuncio de particular (al menos una si EXIGIR… está activo).
# Orden: frases largas antes que subcadenas.
PALABRAS_PARTICULAR = [
    "particular vende",
    "vendo particular",
    "alquiler particular",
    "de particular",
    "sin intermediarios",
    "trato directo",
    "trato directo con propietario",
    "directo propietario",
    "directo dueño",
    "contactar directo",
    "sin comisión",
    "sin comisiones",
    "sin intermediario",
    "sin intermediarios",
    "propietario",
    "propietaria",
    "particulares",
    "particular",
    "dueño",
    "dueña",
    "dueño directo",
    "propietario directo",
    "particular directo",
    "vende dueño",
    "alquila dueño",
    "vende propietario",
    "alquila propietario",
    "particular sin comision",
    "dueño sin comision",
    "propietario sin comision",
    "directo sin intermediarios",
    "particular alquila",
    "particular vende piso",
    "dueño alquila piso",
    "propietario alquila piso",
    "sin agencia",
    "sin agencias",
    "sin inmobiliaria",
    "sin inmobiliarias",
    "particular particular",
    "dueño particular",
    "propietario particular",
    "privado",
    "privada",
    "particular privado",
    "dueño privado",
    "propietario privado",
    "particular alquila sin comision",
    "dueño alquila sin comision",
    "propietario alquila sin comision",
    "vendo sin comision",
    "alquilo sin comision",
    "particular vende sin comision",
    "dueño vende sin comision",
    "propietario vende sin comision",
    "trato directo con dueño",
    "trato directo con propietario",
    "contacto directo con dueño",
    "contacto directo con propietario",
    "llamar directamente al dueño",
    "llamar directamente al propietario",
    "hablar directamente con dueño",
    "hablar directamente con propietario",
    "sin costes de agencia",
    "sin gastos de agencia",
    "sin comision de agencia",
    "sin comision de inmobiliaria",
    "alquiler directo dueño",
    "alquiler directo propietario",
    "venta directa dueño",
    "venta directa propietario",
    "particular alquila directamente",
    "particular vende directamente",
    "dueño alquila directamente",
    "dueño vende directamente",
    "propietario alquila directamente",
    "propietario vende directamente",
    "sin intermediarios de pago",
    "sin comisiones de intermediacion",
    "contacto particular",
    "contacto dueño",
    "contacto propietario",
    "llamar dueño",
    "llamar propietario",
    "telefono particular",
    "telefono dueño",
    "telefono propietario",
    "móvil particular",
    "móvil dueño",
    "móvil propietario",
    "whatsapp particular",
    "whatsapp dueño",
    "whatsapp propietario",
    "particular no profesional",
    "dueño no profesional",
    "propietario no profesional",
    "particular sin empresa",
    "dueño sin empresa",
    "propietario sin empresa",
    "particular independiente",
    "dueño independiente",
    "propietario independiente",
    "vivienda de particular",
    "piso de particular",
    "chalet de particular",
    "ático de particular",
    "dúplex de particular",
    "estudio de particular",
    "loft de particular",
    "garaje de particular",
    "trastero de particular",
    "local de particular",
    "nave de particular",
    "terreno de particular",
    "solar de particular",
    "finca de particular",
    "parcela de particular",
    "casa de particular",
    "apartamento de particular",
    "vivienda de dueño",
    "piso de dueño",
    "chalet de dueño",
    "ático de dueño",
    "dúplex de dueño",
    "estudio de dueño",
    "loft de dueño",
    "garaje de dueño",
    "trastero de dueño",
    "local de dueño",
    "nave de dueño",
    "terreno de dueño",
    "solar de dueño",
    "finca de dueño",
    "parcela de dueño",
    "casa de dueño",
    "apartamento de dueño",
    "vivienda de propietario",
    "piso de propietario",
    "chalet de propietario",
    "ático de propietario",
    "dúplex de propietario",
    "estudio de propietario",
    "loft de propietario",
    "garaje de propietario",
    "trastero de propietario",
    "local de propietario",
    "nave de propietario",
    "terreno de propietario",
    "solar de propietario",
    "finca de propietario",
    "parcela de propietario",
    "casa de propietario",
    "apartamento de propietario",
]

# Refuerzo: agencia (inmobiliaria ya está en portales_comun)
PALABRAS_AGENCIA_EXTRA = [
    "agencia",
    "llámanos",
    "llamanos",
    "asesoramiento inmobiliario",
    "equipo comercial",
    "captación",
    "contacta",
    "contacto",
    "teléfono",
    "telefono",
    "llamar",
    "llame",
    "consulta",
    "información",
    "informacion",
    "visita",
    "visitar",
    "cita",
    "citar",
    "asesor",
    "asesora",
    "asesores",
    "comercial",
    "comerciales",
    "agente",
    "agentes",
    "broker",
    "brokers",
    "consultor",
    "consultora",
    "consultores",
    "gestor",
    "gestora",
    "gestores",
    "administrador",
    "administradora",
    "administradores",
    "empresa",
    "empresas",
    "negocio",
    "negocios",
    "profesional",
    "profesionales",
    "servicio",
    "servicios",
    "atención",
    "atencion",
    "cliente",
    "clientes",
    "venta",
    "vendedor",
    "vendedora",
    "vendedores",
    "team",
    "equipo",
    "staff",
    "personal",
    "oficina",
    "oficinas",
    "central",
    "centro",
    "contact",
    "contactar",
    "llamada",
    "llamadas",
    "phone",
    "móvil",
    "movil",
    "whatsapp",
    "email",
    "mail",
    "correo",
    "web",
    "página",
    "pagina",
    "sitio",
    "online",
    "digital",
    "portal",
    "portales",
    "plataforma",
    "plataformas",
    "redes",
    "social",
    "facebook",
    "instagram",
    "twitter",
    "linkedin",
    "youtube",
    "tiktok",
    "inmob",
    "inmo",
    "inmo.",
    "inmob.",
    "inmobiliario",
    "inmobiliaria.",
    "inmobiliarios",
    "inmobiliarias",
    "real",
    "estate",
    "realstate",
    "real-estate",
    "realestate",
    "properties",
    "property",
    "homes",
    "home",
    "house",
    "houses",
    "apartments",
    "apartment",
    "flats",
    "flat",
    "viviendas",
    "vivienda",
    "piso",
    "pisos",
    "chalet",
    "chalets",
    "ático",
    "aticos",
    "dúplex",
    "duplex",
    "estudio",
    "estudios",
    "loft",
    "lofts",
    "garaje",
    "garajes",
    "trastero",
    "trasteros",
    "local",
    "locales",
    "oficina",
    "oficinas",
    "nave",
    "naves",
    "terreno",
    "terrenos",
    "solar",
    "solares",
    "finca",
    "fincas",
    "parcela",
    "parcelas",
    "rustica",
    "rustico",
    "rústica",
    "rústico",
    "urban",
    "urbana",
    "industrial",
    "comercial",
    "residencial",
    "residenciales",
    "turístico",
    "turistico",
    "turistica",
    "vacacional",
    "segunda mano",
    "segunda mano",
    "nueva construcción",
    "nueva construccion",
    "obra nueva",
    "estreno",
    "estrenar",
    "promoción",
    "promocion",
    "promo",
    "promotor",
    "promotora",
    "desarrollador",
    "desarrolladora",
    "constructora",
    "constructor",
    "construcción",
    "construccion",
    "reforma",
    "reformas",
    "reformado",
    "reformada",
    "restaurado",
    "restaurada",
    "restauración",
    "restauracion",
    "diseño",
    "diseño interior",
    "diseño",
    "arquitecto",
    "arquitecta",
    "arquitectos",
    "decorador",
    "decoradora",
    "decoradores",
    "interiorista",
    "interioristas",
    "diseñador",
    "diseñadora",
    "diseñadores",
    "mobiliario",
    "muebles",
    "amueblado",
    "amueblada",
    "sin amueblar",
    "sin amueblar",
    "amueblar",
    "equipado",
    "equipada",
    "sin equipar",
    "sin equipar",
    "equipar",
    "cocina",
    "cocinas",
    "baño",
    "baños",
    "aseos",
    "terraza",
    "terrazas",
    "balcón",
    "balcon",
    "balcones",
    "jardín",
    "jardin",
    "jardines",
    "piscina",
    "piscinas",
    "garaje",
    "garajes",
    "parking",
    "parkings",
    "trastero",
    "trasteros",
    "ascensor",
    "ascensores",
    "calefacción",
    "calefaccion",
    "aire acondicionado",
    "aire",
    "acondicionado",
    "aire acondicionado",
    "calefacción",
    "calefaccion",
    "gas",
    "gasto",
    "gastos",
    "comunidad",
    "comunidades",
    "ibí",
    "ibi",
    "plusvalía",
    "plusvalia",
    "impuestos",
    "impuesto",
    "tasación",
    "tasacion",
    "valor",
    "valores",
    "precio",
    "precios",
    "coste",
    "costes",
    "inversión",
    "inversion",
    "rentabilidad",
    "renta",
    "rentar",
    "alquilar",
    "alquiler",
    "alquilado",
    "alquilada",
    "arrendar",
    "arrendamiento",
    "arrendado",
    "arrendada",
    "contrato",
    "contratos",
    "fianza",
    "fianzas",
    "depósito",
    "depositos",
    "mensual",
    "mensuales",
    "mes",
    "meses",
    "año",
    "años",
    "día",
    "días",
    "semana",
    "semanas",
    "inmediato",
    "inmediata",
    "urgente",
    "urgentes",
    "rápido",
    "rapida",
    "rápidos",
    "rapidas",
    "inmediato",
    "inmediatos",
    "inmediatas",
    "disponible",
    "disponibles",
    "disponibilidad",
    "libre",
    "libres",
    "ocupado",
    "ocupados",
    "ocupada",
    "ocupadas",
    "vacío",
    "vacio",
    "vacíos",
    "vacios",
    "nuevo",
    "nueva",
    "nuevos",
    "nuevas",
    "antiguo",
    "antigua",
    "antiguos",
    "antiguas",
    "moderno",
    "moderna",
    "modernos",
    "modernas",
    "antiguo",
    "antigua",
    "antiguos",
    "antiguas",
    "reformado",
    "reformada",
    "reformados",
    "reformadas",
    "buen estado",
    "buen estado",
    "muy buen estado",
    "muy buen estado",
    "a estrenar",
    "a estrenar",
    "seminuevo",
    "seminueva",
    "seminuevos",
    "seminuevas",
    "segunda mano",
    "segunda mano",
    "ocasión",
    "ocasion",
    "oportunidad",
    "oportunidades",
    "chollo",
    "chollos",
    "oferta",
    "ofertas",
    "rebaja",
    "rebajas",
    "descuento",
    "descuentos",
    "barato",
    "barata",
    "baratos",
    "baratas",
    "económico",
    "economico",
    "económica",
    "economica",
    "económicos",
    "economicos",
    "económicas",
    "economicas",
    "asequible",
    "asequibles",
    "accesible",
    "accesibles",
    "financiado",
    "financiada",
    "financiados",
    "financiadas",
    "financiación",
    "financiacion",
    "hipoteca",
    "hipotecas",
    "préstamo",
    "prestamo",
    "préstamos",
    "prestamos",
    "banco",
    "bancos",
    "caja",
    "cajas",
    "entidad",
    "entidades",
    "financiera",
    "financieras",
    "financiero",
    "financieros",
    "crédito",
    "credito",
    "créditos",
    "creditos",
    "banca",
    "banca",
    "bancario",
    "bancaria",
    "bancarios",
    "bancarias",
    "financiero",
    "financiera",
    "financieros",
    "financieras",
    "dinero",
    "euros",
    "eur",
    "euro",
    "pesetas",
    "peseta",
    "moneda",
    "monedas",
    "cambio",
    "cambios",
    "tipo",
    "tipos",
    "tasa",
    "tasas",
    "interés",
    "interes",
    "intereses",
    "cuota",
    "cuotas",
    "pago",
    "pagos",
    "pagar",
    "pagado",
    "pagada",
    "pagados",
    "pagadas",
    "abono",
    "abonos",
    "abonado",
    "abonada",
    "abonados",
    "abonadas",
    "ingreso",
    "ingresos",
    "entrada",
    "entradas",
    "inicial",
    "iniciales",
    "reserva",
    "reservas",
    "aparte",
    "apartes",
    "apartar",
    "apartado",
    "apartada",
    "apartados",
    "apartadas",
    "señal",
    "senal",
    "seña",
    "senya",
    "señales",
    "senales",
    "señas",
    "senyas",
    "confirmación",
    "confirmacion",
    "confirmado",
    "confirmada",
    "confirmados",
    "confirmadas",
    "reservado",
    "reservada",
    "reservados",
    "reservadas",
    "anotado",
    "anotada",
    "anotados",
    "anotadas",
    "apuntado",
    "apuntada",
    "apuntados",
    "apuntadas",
    "inscrito",
    "inscrita",
    "inscritos",
    "inscritas",
    "registrado",
    "registrada",
    "registrados",
    "registradas",
    "matriculado",
    "matriculada",
    "matriculados",
    "matriculadas",
    "certificado",
    "certificada",
    "certificados",
    "certificadas",
    "legal",
    "legales",
    "legalizado",
    "legalizada",
    "legalizados",
    "legalizadas",
    "registrado",
    "registrada",
    "registrados",
    "registradas",
    "inscrito",
    "inscrita",
    "inscritos",
    "inscritas",
    "matriculado",
    "matriculada",
    "matriculados",
    "matriculadas",
    "catastro",
    "catastral",
    "catastrales",
    "registro",
    "registral",
    "registrales",
    "notaría",
    "notaria",
    "notario",
    "notaria",
    "notarios",
    "notarias",
    "protocolo",
    "protocolos",
    "escritura",
    "escrituras",
    "título",
    "titulo",
    "títulos",
    "titulos",
    "propiedad",
    "propiedades",
    "propietario",
    "propietaria",
    "propietarios",
    "propietarias",
    "dueño",
    "dueña",
    "dueños",
    "dueñas",
    "titular",
    "titular",
    "titulares",
    "copropietario",
    "copropietaria",
    "copropietarios",
    "copropietarias",
    "comunidad",
    "comunidades",
    "vecinos",
    "vecinas",
    "vecindario",
    "urbanización",
    "urbanizacion",
    "urbanizaciones",
    "polígono",
    "poligono",
    "polígonos",
    "poligonos",
    "parcela",
    "parcelas",
    "solar",
    "solares",
    "terreno",
    "terrenos",
    "suelo",
    "suelos",
    "calle",
    "calles",
    "avenida",
    "avenidas",
    "plaza",
    "plazas",
    "paseo",
    "paseos",
    "ronda",
    "rondas",
    "carrera",
    "carreras",
    "camino",
    "caminos",
    "carretera",
    "carreteras",
    "autopista",
    "autopistas",
    "autovía",
    "autovia",
    "autovías",
    "autovias",
    "nacional",
    "nacionales",
    "comarcal",
    "comarcales",
    "provincial",
    "provinciales",
    "local",
    "locales",
    "municipal",
    "municipales",
    "urbano",
    "urbanos",
    "rústico",
    "rustico",
    "rústicos",
    "rusticos",
    "agrícola",
    "agricola",
    "agrícolas",
    "agricolas",
    "ganadero",
    "ganadera",
    "ganaderos",
    "ganaderas",
    "forestal",
    "forestales",
    "industrial",
    "industriales",
    "comercial",
    "comerciales",
    "residencial",
    "residenciales",
    "turístico",
    "turistico",
    "turísticos",
    "turisticos",
    "turística",
    "turistica",
    "turísticas",
    "turisticas",
    "vacacional",
    "vacacionales",
    "segunda residencia",
    "segunda residencia",
    "primera residencia",
    "primera residencia",
    "vivienda habitual",
    "vivienda habitual",
    "vivienda secundaria",
    "vivienda secundaria",
    "uso residencial",
    "uso residencial",
    "uso comercial",
    "uso comercial",
    "uso industrial",
    "uso industrial",
    "uso oficinas",
    "uso oficinas",
    "uso local",
    "uso local",
    "uso nave",
    "uso nave",
    "uso garaje",
    "uso garaje",
    "uso trastero",
    "uso trastero",
    "uso almacen",
    "uso almacen",
    "uso depósito",
    "uso deposito",
    "uso parking",
    "uso parking",
    "suelo urbanizable",
    "suelo urbanizable",
    "suelo urbano",
    "suelo urbano",
    "suelo rústico",
    "suelo rustico",
    "suelo urbanizado",
    "suelo urbanizado",
    "suelo sin urbanizar",
    "suelo sin urbanizar",
    "terreno urbanizable",
    "terreno urbanizable",
    "terreno urbano",
    "terreno urbano",
    "terreno rústico",
    "terreno rustico",
    "terreno urbanizado",
    "terreno urbanizado",
    "terreno sin urbanizar",
    "terreno sin urbanizar",
    "solar urbanizable",
    "solar urbanizable",
    "solar urbano",
    "solar urbano",
    "solar rústico",
    "solar rustico",
    "solar urbanizado",
    "solar urbanizado",
    "solar sin urbanizar",
    "solar sin urbanizar",
    "parcela urbanizable",
    "parcela urbanizable",
    "parcela urbana",
    "parcela urbana",
    "parcela rústica",
    "parcela rustica",
    "parcela urbanizada",
    "parcela urbanizada",
    "parcela sin urbanizar",
    "parcela sin urbanizar",
    "finca urbanizable",
    "finca urbanizable",
    "finca urbana",
    "finca urbana",
    "finca rústica",
    "finca rustica",
    "finca urbanizada",
    "finca urbanizada",
    "finca sin urbanizar",
    "finca sin urbanizar",
]


def es_particular(texto: str) -> bool:
    """
    True solo si parece anuncio de particular:
    - rechaza señales claras de agencia / inmobiliaria
    - si EXIGIR_PALABRA_PARTICULAR_EN_TITULO: exige al menos una PALABRAS_PARTICULAR
    """
    t = texto.lower()

    for palabra in PALABRAS_INMOBILIARIA:
        if len(palabra) <= 3:
            continue
        if palabra in t:
            return False

    for palabra in PALABRAS_AGENCIA_EXTRA:
        if palabra in t:
            return False

    for palabra in PALABRAS_PARTICULAR:
        if palabra in t:
            return True

    if getattr(config, "EXIGIR_PALABRA_PARTICULAR_EN_TITULO", True):
        return False

    return True
