#!/usr/bin/env python3
"""
Guía súper fácil para PythonAnywhere - Paso a paso con imágenes mentales
"""

def guia_pythonanywhere_facil():
    """Guía simplificada para PythonAnywhere"""
    
    print("GUÍA PYTHONANYWHERE - MUY FÁCIL")
    print("=" * 40)
    print()
    
    print("PROBLEMA: PythonAnywhere parece complicado")
    print("SOLUCIÓN: Lo hacemos paso a paso, fácil y claro")
    print()
    
    print("PASO 1: REGISTRO (3 minutos)")
    print("-" * 30)
    print("1. Abre Chrome/Safari en tu móvil")
    print("2. Ve a: www.pythonanywhere.com")
    print("3. Haz clic en 'Sign up' (arriba derecha)")
    print("4. Rellena:")
    print("   - Username: elige algo único (ej: damianbot2024)")
    print("   - Email: tu email real")
    print("   - Password: algo que recuerdes")
    print("5. Haz clic en 'Sign up'")
    print("6. Revisa tu email y haz clic en el enlace de verificación")
    print("7. Listo! Ya tienes cuenta")
    print()
    
    print("PASO 2: PRIMER INICIO (2 minutos)")
    print("-" * 30)
    print("1. Inicia sesión en pythonanywhere.com")
    print("2. Verás un dashboard con muchas opciones")
    print("3. No te abrumes, solo busca esto:")
    print("   - Consoles (en el menú izquierdo)")
    print("   - Haz clic en 'Bash'")
    print("4. Espera a que cargue una terminal")
    print()
    
    print("PASO 3: SUBIR CÓDIGO (5 minutos)")
    print("-" * 30)
    print("1. En la terminal que se abrió, escribe:")
    print("   git clone https://github.com/damianortells4-code/bot-inmobiliario-2.0")
    print("2. Presiona Enter")
    print("3. Espera a que descargue (verás 'Cloning into...')")
    print("4. Cuando termine, escribe:")
    print("   cd bot-inmobiliario-2.0")
    print("5. Presiona Enter")
    print("6. Ahora instala lo necesario:")
    print("   pip3 install -r requirements.txt")
    print("7. Espera a que instale todo (puede tardar 2-3 minutos)")
    print()
    
    print("PASO 4: CONFIGURAR TELEGRAM (3 minutos)")
    print("-" * 30)
    print("1. En el menú izquierdo, haz clic en 'Files'")
    print("2. Verás una carpeta 'bot-inmobiliario-2.0'")
    print("3. Haz clic en esa carpeta")
    print("4. Busca el archivo 'config.py' y haz clic en él")
    print("5. Verás el código del archivo")
    print("6. Al final del archivo, añade:")
    print("   # Mis variables de Telegram")
    print("   TELEGRAM_BOT_TOKEN = 'pon_aqui_tu_token'")
    print("   TELEGRAM_CHAT_ID = 'pon_aqui_tu_chat_id'")
    print("7. Reemplaza 'pon_aqui_tu_token' con tu token real")
    print("8. Reemplaza 'pon_aqui_tu_chat_id' con tu chat ID real")
    print("9. Haz clic en 'Save' (arriba)")
    print()
    
    print("PASO 5: PROBAR EL BOT (2 minutos)")
    print("-" * 30)
    print("1. Vuelve a 'Consoles' > 'Bash'")
    print("2. Asegúrate que estás en la carpeta correcta:")
    print("   cd bot-inmobiliario-2.0")
    print("3. Ejecuta el bot:")
    print("   python3 main.py")
    print("4. Deberías ver:")
    print("   'Bot inmobiliario iniciado...'")
    print("   'Base de datos: anuncios.db'")
    print("5. Si ves errores, avísame y te ayudo")
    print("6. Si funciona, recibirás notificaciones en Telegram")
    print("7. Presiona Ctrl+C para detenerlo")
    print()
    
    print("PASO 6: AUTOMATIZAR (3 minutos)")
    print("-" * 30)
    print("1. En el menú izquierdo, haz clic en 'Tasks'")
    print("2. Haz clic en 'Create a new task'")
    print("3. Configura así:")
    print("   - Description: Bot Inmobiliario")
    print("   - Type: Python")
    print("   - Command: /home/tuusuario/bot-inmobiliario-2.0/main.py")
    print("   - Schedule: Every 10 minutes")
    print("   - Hour: 08:00 - 20:00")
    print("4. Haz clic en 'Create'")
    print("5. Listo! El bot se ejecutará solo")
    print()
    
    print("¿QUÉ HAGO SI NO FUNCIONA?")
    print("-" * 30)
    print("PROBLEMA 1: 'git: command not found'")
    print("Solución: Ve a Consoles > Bash, no otras consolas")
    print()
    print("PROBLEMA 2: 'No such file or directory'")
    print("Solución: Asegúrate que escribiste bien el git clone")
    print()
    print("PROBLEMA 3: 'pip3: command not found'")
    print("Solución: Usa 'pip' en lugar de 'pip3'")
    print()
    print("PROBLEMA 4: 'ModuleNotFoundError'")
    print("Solución: Espera a que termine de instalar requirements.txt")
    print()
    print("PROBLEMA 5: 'No recibo notificaciones'")
    print("Solución: Verifica tu TOKEN y CHAT_ID en config.py")
    print()
    
    print("ALTERNATIVA MÁS FÁCIL: REPLIT")
    print("-" * 30)
    print("Si PythonAnywhere es muy complicado:")
    print("1. Ve a replit.com")
    print("2. Regístrate (gratis)")
    print("3. Haz clic en 'Create Repl' > 'Python'")
    print("4. Copia y pega tu código allí")
    print("5. Instala dependencias en el shell")
    print("6. Es más visual y fácil")
    print()
    
    print("RESUMEN EN 10 PASOS:")
    print("-" * 20)
    print("1. Regístrate en pythonanywhere.com")
    print("2. Ve a Consoles > Bash")
    print("3. git clone [URL del bot]")
    print("4. cd bot-inmobiliario-2.0")
    print("5. pip3 install -r requirements.txt")
    print("6. Edita config.py con tus datos Telegram")
    print("7. python3 main.py (para probar)")
    print("8. Ve a Tasks > Create new task")
    print("9. Configura para ejecutar cada 10 minutos")
    print("10. Listo! Recibirás notificaciones en móvil")
    print()
    
    print("¿NECESITAS AYUDA EN ALGÚN PASO?")
    print("-" * 30)
    print("Avísame qué paso te da problemas y te ayudo:")
    print("- ¿No puedes registrarte?")
    print("- ¿No encuentras el menú Consoles?")
    print("- ¿Error al clonar el código?")
    print("- ¿Error al instalar dependencias?")
    print("- ¿No funcionan las notificaciones?")
    print()
    
    return "¡Listo para empezar!"

if __name__ == "__main__":
    guia_pythonanywhere_facil()
