"""Cabeceras, pausas y detección de inmobiliaria compartidos entre scrapers."""

import random
import time
from typing import Dict

import requests
from bs4 import BeautifulSoup

import config

PALABRAS_INMOBILIARIA = [
    "inmobiliaria",
    "asesores",
    "real estate",
    "grupo inmobiliario",
    "gestión inmobiliaria",
    "servicios inmobiliarios",
    "api properties",
    "aproperties",
    "nova finques",
    "cèntric finques",
    "goldmark",
    "signature luxury homes",
    "finques",
    "inmobles",
    "inmob",
    "properties",
    "estate",
    "remax",
    "engel",
    "coldwell",
    "keller williams",
    "century 21",
    "oportunidad",
    "inversión",
    "inversion",
    "promo",
    "promoción",
    "urbanismo",
    "construcción",
    "obras nuevas",
    "obra nueva",
    "entrega",
    "llaves en mano",
    "estrenar",
    "promotor",
    "promotora",
    "desarrollador",
    "desarrolladora",
    "construcciones",
    "grupo",
    "holding",
    "capital",
    "investment",
    "s.l.",
    "sl",
    "sa",
    "ltd",
    "company",
    "corp",
    "corporation",
    "administrador",
    "administradora",
    "administradores",
    "fincas",
    "real estate",
    "realstate",
    "inmob",
    "inmo",
    "gestión",
    "gestion",
    "asesor",
    "asesora",
    "asesores",
    "consultor",
    "consultora",
    "consultores",
    "manager",
    "directivo",
    "director",
    "directora",
    "sr",
    "sra",
    "dña",
    "don",
    "profesional",
    "profesionales",
    "empresa",
    "empresas",
    "negocio",
    "negocios",
    "comercial",
    "comerciales",
    "venta",
    "vendedor",
    "vendedora",
    "vendedores",
    "broker",
    "brokers",
    "agent",
    "agents",
    "agente",
    "agentes",
    "team",
    "equipo",
    "staff",
    "personal",
    "oficina",
    "oficinas",
    "central",
    "centro",
    "servicio",
    "servicios",
    "atención",
    "atencion",
    "cliente",
    "clientes",
    "usuario",
    "usuarios",
    "contact",
    "contacto",
    "contactar",
    "llamar",
    "llame",
    "llamen",
    "llamada",
    "llamadas",
    "teléfono",
    "telefono",
    "phone",
    "móvil",
    "movil",
    "whatsapp",
    "email",
    "mail",
    "correo",
    "web",
    "página",
    "pagina",
    "sitio",
    "online",
    "digital",
    "portal",
    "portales",
    "plataforma",
    "plataformas",
    "redes",
    "social",
    "facebook",
    "instagram",
    "twitter",
    "linkedin",
    "youtube",
    "tiktok",
    "inmob",
    "inmo",
    "inmo.",
    "inmob.",
    "inmobiliario",
    "inmobiliaria.",
    "inmobiliarios",
    "inmobiliarias",
    "real",
    "estate",
    "realstate",
    "real-estate",
    "realestate",
    "properties",
    "property",
    "homes",
    "home",
    "house",
    "houses",
    "apartments",
    "apartment",
    "flats",
    "flat",
    "viviendas",
    "vivienda",
    "piso",
    "pisos",
    "chalet",
    "chalets",
    "ático",
    "aticos",
    "dúplex",
    "duplex",
    "estudio",
    "estudios",
    "loft",
    "lofts",
    "garaje",
    "garajes",
    "trastero",
    "trasteros",
    "local",
    "locales",
    "oficina",
    "oficinas",
    "nave",
    "naves",
    "terreno",
    "terrenos",
    "solar",
    "solares",
    "finca",
    "fincas",
    "parcela",
    "parcelas",
    "rustica",
    "rustico",
    "rústica",
    "rústico",
    "urban",
    "urbana",
    "industrial",
    "comercial",
    "residencial",
    "residenciales",
    "turístico",
    "turistico",
    "turistica",
    "vacacional",
    "segunda mano",
    "segunda mano",
    "nueva construcción",
    "nueva construccion",
    "obra nueva",
    "estreno",
    "estrenar",
    "promoción",
    "promocion",
    "promo",
    "promotor",
    "promotora",
    "desarrollador",
    "desarrolladora",
    "constructora",
    "constructor",
    "construcción",
    "construccion",
    "reforma",
    "reformas",
    "reformado",
    "reformada",
    "restaurado",
    "restaurada",
    "restauración",
    "restauracion",
    "diseño",
    "diseño interior",
    "diseño",
    "arquitecto",
    "arquitecta",
    "arquitectos",
    "decorador",
    "decoradora",
    "decoradores",
    "interiorista",
    "interioristas",
    "diseñador",
    "diseñadora",
    "diseñadores",
    "mobiliario",
    "muebles",
    "amueblado",
    "amueblada",
    "sin amueblar",
    "sin amueblar",
    "amueblar",
    "equipado",
    "equipada",
    "sin equipar",
    "sin equipar",
    "equipar",
    "cocina",
    "cocinas",
    "baño",
    "baños",
    "aseos",
    "terraza",
    "terrazas",
    "balcón",
    "balcon",
    "balcones",
    "jardín",
    "jardin",
    "jardines",
    "piscina",
    "piscinas",
    "garaje",
    "garajes",
    "parking",
    "parkings",
    "trastero",
    "trasteros",
    "ascensor",
    "ascensores",
    "calefacción",
    "calefaccion",
    "aire acondicionado",
    "aire",
    "acondicionado",
    "aire acondicionado",
    "calefacción",
    "calefaccion",
    "gas",
    "gasto",
    "gastos",
    "comunidad",
    "comunidades",
    "ibí",
    "ibi",
    "plusvalía",
    "plusvalia",
    "impuestos",
    "impuesto",
    "tasación",
    "tasacion",
    "valor",
    "valores",
    "precio",
    "precios",
    "coste",
    "costes",
    "inversión",
    "inversion",
    "rentabilidad",
    "renta",
    "rentar",
    "alquilar",
    "alquiler",
    "alquilado",
    "alquilada",
    "arrendar",
    "arrendamiento",
    "arrendado",
    "arrendada",
    "contrato",
    "contratos",
    "fianza",
    "fianzas",
    "depósito",
    "depositos",
    "mensual",
    "mensuales",
    "mes",
    "meses",
    "año",
    "años",
    "día",
    "días",
    "semana",
    "semanas",
    "inmediato",
    "inmediata",
    "urgente",
    "urgentes",
    "rápido",
    "rapida",
    "rápidos",
    "rapidas",
    "inmediato",
    "inmediatos",
    "inmediatas",
    "disponible",
    "disponibles",
    "disponibilidad",
    "libre",
    "libres",
    "ocupado",
    "ocupados",
    "ocupada",
    "ocupadas",
    "vacío",
    "vacio",
    "vacíos",
    "vacios",
    "nuevo",
    "nueva",
    "nuevos",
    "nuevas",
    "antiguo",
    "antigua",
    "antiguos",
    "antiguas",
    "moderno",
    "moderna",
    "modernos",
    "modernas",
    "antiguo",
    "antigua",
    "antiguos",
    "antiguas",
    "reformado",
    "reformada",
    "reformados",
    "reformadas",
    "buen estado",
    "buen estado",
    "muy buen estado",
    "muy buen estado",
    "a estrenar",
    "a estrenar",
    "seminuevo",
    "seminueva",
    "seminuevos",
    "seminuevas",
    "segunda mano",
    "segunda mano",
    "ocasión",
    "ocasion",
    "oportunidad",
    "oportunidades",
    "chollo",
    "chollos",
    "oferta",
    "ofertas",
    "rebaja",
    "rebajas",
    "descuento",
    "descuentos",
    "barato",
    "barata",
    "baratos",
    "baratas",
    "económico",
    "economico",
    "económica",
    "economica",
    "económicos",
    "economicos",
    "económicas",
    "economicas",
    "asequible",
    "asequibles",
    "accesible",
    "accesibles",
    "financiado",
    "financiada",
    "financiados",
    "financiadas",
    "financiación",
    "financiacion",
    "hipoteca",
    "hipotecas",
    "préstamo",
    "prestamo",
    "préstamos",
    "prestamos",
    "banco",
    "bancos",
    "caja",
    "cajas",
    "entidad",
    "entidades",
    "financiera",
    "financieras",
    "financiero",
    "financieros",
    "crédito",
    "credito",
    "créditos",
    "creditos",
    "banca",
    "banca",
    "bancario",
    "bancaria",
    "bancarios",
    "bancarias",
    "financiero",
    "financiera",
    "financieros",
    "financieras",
    "dinero",
    "euros",
    "eur",
    "euro",
    "pesetas",
    "peseta",
    "moneda",
    "monedas",
    "cambio",
    "cambios",
    "tipo",
    "tipos",
    "tasa",
    "tasas",
    "interés",
    "interes",
    "intereses",
    "cuota",
    "cuotas",
    "pago",
    "pagos",
    "pagar",
    "pagado",
    "pagada",
    "pagados",
    "pagadas",
    "abono",
    "abonos",
    "abonado",
    "abonada",
    "abonados",
    "abonadas",
    "ingreso",
    "ingresos",
    "entrada",
    "entradas",
    "inicial",
    "iniciales",
    "reserva",
    "reservas",
    "aparte",
    "apartes",
    "apartar",
    "apartado",
    "apartada",
    "apartados",
    "apartadas",
    "señal",
    "senal",
    "seña",
    "senya",
    "señales",
    "senales",
    "señas",
    "senyas",
    "confirmación",
    "confirmacion",
    "confirmado",
    "confirmada",
    "confirmados",
    "confirmadas",
    "reservado",
    "reservada",
    "reservados",
    "reservadas",
    "anotado",
    "anotada",
    "anotados",
    "anotadas",
    "apuntado",
    "apuntada",
    "apuntados",
    "apuntadas",
    "inscrito",
    "inscrita",
    "inscritos",
    "inscritas",
    "registrado",
    "registrada",
    "registrados",
    "registradas",
    "matriculado",
    "matriculada",
    "matriculados",
    "matriculadas",
    "certificado",
    "certificada",
    "certificados",
    "certificadas",
    "legal",
    "legales",
    "legalizado",
    "legalizada",
    "legalizados",
    "legalizadas",
    "registrado",
    "registrada",
    "registrados",
    "registradas",
    "inscrito",
    "inscrita",
    "inscritos",
    "inscritas",
    "matriculado",
    "matriculada",
    "matriculados",
    "matriculadas",
    "catastro",
    "catastral",
    "catastrales",
    "registro",
    "registral",
    "registrales",
    "notaría",
    "notaria",
    "notario",
    "notaria",
    "notarios",
    "notarias",
    "protocolo",
    "protocolos",
    "escritura",
    "escrituras",
    "título",
    "titulo",
    "títulos",
    "titulos",
    "propiedad",
    "propiedades",
    "propietario",
    "propietaria",
    "propietarios",
    "propietarias",
    "dueño",
    "dueña",
    "dueños",
    "dueñas",
    "titular",
    "titular",
    "titulares",
    "copropietario",
    "copropietaria",
    "copropietarios",
    "copropietarias",
    "comunidad",
    "comunidades",
    "vecinos",
    "vecinas",
    "vecindario",
    "urbanización",
    "urbanizacion",
    "urbanizaciones",
    "polígono",
    "poligono",
    "polígonos",
    "poligonos",
    "parcela",
    "parcelas",
    "solar",
    "solares",
    "terreno",
    "terrenos",
    "suelo",
    "suelos",
    "calle",
    "calles",
    "avenida",
    "avenidas",
    "plaza",
    "plazas",
    "paseo",
    "paseos",
    "ronda",
    "rondas",
    "carrera",
    "carreras",
    "camino",
    "caminos",
    "carretera",
    "carreteras",
    "autopista",
    "autopistas",
    "autovía",
    "autovia",
    "autovías",
    "autovias",
    "nacional",
    "nacionales",
    "comarcal",
    "comarcales",
    "provincial",
    "provinciales",
    "local",
    "locales",
    "municipal",
    "municipales",
    "urbano",
    "urbanos",
    "rústico",
    "rustico",
    "rústicos",
    "rusticos",
    "agrícola",
    "agricola",
    "agrícolas",
    "agricolas",
    "ganadero",
    "ganadera",
    "ganaderos",
    "ganaderas",
    "forestal",
    "forestales",
    "industrial",
    "industriales",
    "comercial",
    "comerciales",
    "residencial",
    "residenciales",
    "turístico",
    "turistico",
    "turísticos",
    "turisticos",
    "turística",
    "turistica",
    "turísticas",
    "turisticas",
    "vacacional",
    "vacacionales",
    "segunda residencia",
    "segunda residencia",
    "primera residencia",
    "primera residencia",
    "vivienda habitual",
    "vivienda habitual",
    "vivienda secundaria",
    "vivienda secundaria",
    "uso residencial",
    "uso residencial",
    "uso comercial",
    "uso comercial",
    "uso industrial",
    "uso industrial",
    "uso oficinas",
    "uso oficinas",
    "uso local",
    "uso local",
    "uso nave",
    "uso nave",
    "uso garaje",
    "uso garaje",
    "uso trastero",
    "uso trastero",
    "uso almacen",
    "uso almacen",
    "uso depósito",
    "uso deposito",
    "uso parking",
    "uso parking",
    "suelo urbanizable",
    "suelo urbanizable",
    "suelo urbano",
    "suelo urbano",
    "suelo rústico",
    "suelo rustico",
    "suelo urbanizado",
    "suelo urbanizado",
    "suelo sin urbanizar",
    "suelo sin urbanizar",
    "terreno urbanizable",
    "terreno urbanizable",
    "terreno urbano",
    "terreno urbano",
    "terreno rústico",
    "terreno rustico",
    "terreno urbanizado",
    "terreno urbanizado",
    "terreno sin urbanizar",
    "terreno sin urbanizar",
    "solar urbanizable",
    "solar urbanizable",
    "solar urbano",
    "solar urbano",
    "solar rústico",
    "solar rustico",
    "solar urbanizado",
    "solar urbanizado",
    "solar sin urbanizar",
    "solar sin urbanizar",
    "parcela urbanizable",
    "parcela urbanizable",
    "parcela urbana",
    "parcela urbana",
    "parcela rústica",
    "parcela rustica",
    "parcela urbanizada",
    "parcela urbanizada",
    "parcela sin urbanizar",
    "parcela sin urbanizar",
    "finca urbanizable",
    "finca urbanizable",
    "finca urbana",
    "finca urbana",
    "finca rústica",
    "finca rustica",
    "finca urbanizada",
    "finca urbanizada",
    "finca sin urbanizar",
    "finca sin urbanizar",
]

USER_AGENTS = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
]

def get_random_headers():
    """Genera headers aleatorios para evitar detección"""
    return {
        "User-Agent": random.choice(USER_AGENTS),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Language": random.choice(["es-ES,es;q=0.9,en;q=0.8", "en-US,en;q=0.9,es;q=0.8", "es-ES,es;q=0.9,en-GB;q=0.8,en;q=0.7"]),
        "Accept-Encoding": "gzip, deflate, br",
        "DNT": "1",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "none",
        "Sec-Fetch-User": "?1",
        "Cache-Control": "max-age=0",
    }

REQUEST_TIMEOUT = 25


def pausa_entre_peticiones():
    """Pausa aleatoria entre peticiones para evitar detección."""
    # Pausa más larga y aleatoria para simular comportamiento humano
    pausa = random.uniform(config.SCRAPER_PAUSA_MIN, config.SCRAPER_PAUSA_MAX)
    
    # Añadir variación extra para evitar patrones
    if random.random() < 0.3:  # 30% de probabilidad de pausa extra
        pausa += random.uniform(1.0, 3.0)
    
    print(f"   (pausa {pausa:.1f}s)")
    time.sleep(pausa)


def pausa_entre_fuentes():
    """Entre pisos / fotocasa / DDG para no encadenar ráfagas."""
    mn = float(getattr(config, "PAUSA_ENTRE_FUENTES_MIN", 8.0))
    mx = float(getattr(config, "PAUSA_ENTRE_FUENTES_MAX", 18.0))
    if mx < mn:
        mx = mn
    
    # Pausa con variación extra
    pausa = random.uniform(mn, mx)
    
    # 25% de probabilidad de pausa extra larga
    if random.random() < 0.25:
        pausa += random.uniform(2.0, 5.0)
    
    print(f"   (pausa entre fuentes {pausa:.1f}s)")
    time.sleep(pausa)


def titulo_sugiere_inmobiliaria(titulo: str) -> bool:
    t = titulo.lower()
    for palabra in PALABRAS_INMOBILIARIA:
        if len(palabra) <= 3:
            continue
        if palabra in t:
            return True
    return False


def texto_visible_sin_scripts(soup: BeautifulSoup) -> str:
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()
    return soup.get_text().lower()


def es_inmobiliaria(
    session: requests.Session, link: str, cache: Dict[str, bool]
) -> bool:
    if link in cache:
        return cache[link]

    try:
        pausa_entre_peticiones()
        response = _get_con_reintento(session, link)

        soup = BeautifulSoup(response.text, "html.parser")
        texto = texto_visible_sin_scripts(soup)

        for palabra in PALABRAS_INMOBILIARIA:
            if palabra in texto:
                cache[link] = True
                return True

        cache[link] = False
        return False

    except (requests.RequestException, OSError):
        cache[link] = False
        return False


def _get_con_reintento(session: requests.Session, url: str) -> requests.Response:
    """GET con reintentos y manejo de 403"""
    max_retries = 3
    base_wait = 2
    
    for attempt in range(max_retries):
        try:
            # Usar headers aleatorios en cada intento
            headers = get_random_headers()
            r = session.get(url, timeout=REQUEST_TIMEOUT, headers=headers)
            
            if r.status_code == 429:
                espera = random.uniform(50, 100)
                print(f"   (429: esperando {espera:.0f}s…)")
                time.sleep(espera)
                continue
            elif r.status_code == 403:
                if attempt < max_retries - 1:
                    espera = base_wait * (2 ** attempt) + random.uniform(5, 15)
                    print(f"   (403: reintentando en {espera:.1f}s - intento {attempt + 1}/{max_retries})")
                    time.sleep(espera)
                    continue
                else:
                    print(f"   (403: bloqueado después de {max_retries} intentos)")
                    r.raise_for_status()
            
            r.raise_for_status()
            return r
            
        except requests.RequestException as e:
            if attempt < max_retries - 1:
                espera = base_wait * (2 ** attempt) + random.uniform(1, 3)
                print(f"   (Error {e}: reintentando en {espera:.1f}s - intento {attempt + 1}/{max_retries})")
                time.sleep(espera)
                continue
            else:
                raise


def get_listado(session: requests.Session, url: str) -> requests.Response:
    """GET de página de listado con pausa previa y reintento ante 429."""
    pausa_entre_peticiones()
    return _get_con_reintento(session, url)
